### ISSUE TITLE
result change

### ISSUE THREAD

**Issue by Roooook1E** [TomVeniat/SANAS#3]
Hi, 
I am trying to predict a .wav file which include a word, but the model gives very different results between several tests. So I want to ask you the reason that resulted in the situation.
Thanks a lot.

**Comment by TomVeniat** [comment]
Hi, 
Sorry for the delay, could you give a bit more context please?
By default, the architecture is deterministic only in eval mode.
So if you're using the model in training mode, different architectures could be used between runs using the same data, resulting in different predictions.
